# Generated by Django 5.0.6 on 2024-06-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('gst', models.CharField(max_length=15, verbose_name='GST Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Bill')),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
            },
        ),
    ]
