# Generated by Django 5.0.6 on 2024-06-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi-automatic', 'Semi-Automatic')], default='manual', max_length=20)),
                ('inspection_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('reg_year', models.IntegerField()),
                ('km_driven', models.IntegerField()),
                ('rto', models.CharField(max_length=100)),
                ('insurance_validity', models.DateField()),
                ('insurance_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('third-party', 'Third Party'), ('own-damage', 'Own Damage')], default='comprehensive', max_length=20)),
                ('no_of_owners', models.IntegerField()),
                ('finance_available', models.BooleanField(default=False)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('last_date_to_apply', models.DateField()),
            ],
        ),
    ]
