# Generated by Django 5.0.6 on 2024-06-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='happiness_club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_image', models.ImageField(blank=True, upload_to='happiness_club/')),
                ('owner_info', models.CharField(max_length=100)),
                ('testimonial', models.CharField(max_length=200)),
            ],
        ),
    ]
